//3.1
SELECT EMPLOYEE_ID
FROM EMPLOYEES A
LEFT JOIN ORDERS B
ON A.EMPLOYEE_ID = B.ORDER_ID
WHERE B.ORDER_ID IS NULL;

//3.2
SELECT REGION_NAME
FROM REGIONS A
LEFT JOIN WAREHOUSES B
ON A.REGION_ID = B.WAREHOUSE_ID
WHERE B.WAREHOUSE_ID IS NULL;

//3.3
SELECT A.CUSTOMER_ID, A."NAME", A."ADDRESS", A."WEBSITE", A."CREDIT_LIMIT"
FROM CUSTOMERS A
LEFT JOIN ORDERS B
ON A.CUSTOMER_ID = B.ORDER_ID
WHERE B.ORDER_ID IS NULL;

//3.4
SELECT A.ADDRESS AS ADDRESS
FROM CUSTOMERS A
UNION ALL
SELECT B.ADDRESS||', '||B.CITY||', '||B.STATE AS ADRESS
FROM LOCATIONS B
INNER JOIN WAREHOUSES C
ON B.LOCATION_ID = C.LOCATION_ID
ORDER BY ADDRESS;

//3.5
SELECT A."NAME" AS Full_name, 'CUSTOMERS' AS TYPE_PERS
FROM CUSTOMERS A
UNION ALL
SELECT FIRST_NAME||' '|| LAST_NAME AS Full_name, 'EMPLOYEES' AS TYPE_PERS
FROM EMPLOYEES
ORDER BY Full_name;