 
//2.1
SELECT DISTINCT PRODUCT_ID,PRODUCT_NAME,CATEGORY_NAME

FROM PRODUCTS, PRODUCT_CATEGORIES 

WHERE CATEGORY_NAME LIKE '%Mother Board%' AND PRODUCTS.CATEGORY_ID=PRODUCT_CATEGORIES.CATEGORY_ID; 

 
//2.2
SELECT DISTINCT WAREHOUSE_NAME 

FROM WAREHOUSES,COUNTRIES,REGIONS,LOCATIONS  

WHERE WAREHOUSES.LOCATION_ID = LOCATIONS.LOCATION_ID AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID    

AND COUNTRIES.REGION_ID =REGIONS.REGION_ID AND REGIONS.REGION_NAME LIKE '%Asia%'; 

//2.3
SELECT DISTINCT EMPLOYEE_ID 

FROM ORDERS,EMPLOYEES 

WHERE ORDERS.SALESMAN_ID=EMPLOYEES.EMPLOYEE_ID AND ORDERS.ORDER_DATE> EMPLOYEES.HIRE_DATE  

AND ORDERS.ORDER_DATE BETWEEN EMPLOYEES.HIRE_DATE AND ADD_MONTHS(EMPLOYEES.HIRE_DATE,3) AND ORDERS.STATUS LIKE '%Shipped%'; 

//2.4
SELECT DISTINCT ORDERS.ORDER_ID,QUANTITY 

FROM ORDERS,ORDER_ITEMS 

WHERE ORDER_ITEMS.ORDER_ID=ORDERS.ORDER_ID AND EXTRACT(YEAR FROM ORDERS.ORDER_DATE) = 2017 ; 

//2.5
SELECT DISTINCT LAST_NAME,FIRST_NAME, EMPLOYEE_ID, HIRE_DATE AS INFORMATION_EMPLOYEES 

FROM EMPLOYEES 

WHERE EXTRACT(YEAR FROM HIRE_DATE) > 2016; 